export enum ActionTypes {
  ADD_FAVOURITES = "ADD_FAVOURITES",
  DELETE_FAVOURITES = "DELETE_FAVOURITES",
  DECREAMENT_FAVOURITES = "DECREAMENT_FAVOURITES",
  RESET_FAVOURITES = "RESET_FAVOURITES",
}
