export const navbar = [
    {
        id:"home",
        name:"home",
        url:"/home"
    },
    {
        id:"dishes",
        name:"dishes",
        url:"/dishes"
    },
    {
        id:"about",
        name:"about",
        url:"/about"
    },
    {
        id:"menu",
        name:"menu",
        url:"/menu"
    },
    {
        id:"review",
        name:"review",
        url:"/review"
    },
    {
        id:"order",
        name:"order",
        url:"/order"
    }

];
